#!/usr/bin/env php
<?php
/**
 * Command-line Elegy.
 *
 * PHP version 7
 *
 * @category   Script
 *
 * @author     Francesco Bianco <bianco@javanile.org>
 * @license    https://goo.gl/KPZ2qI  MIT License
 * @copyright  2015-2020 Javanile.org
 */

require_once __DIR__.'/../../../autoload.php';

(new Javanile\DocForge\Compiler())->run($argv);
